name: milestone

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  set-milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get milestone from pom.xml
        run: |
          echo "MILESTONE_NUMBER=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | cut -d- -f1)" >> $GITHUB_ENV

      - name: Set milestone to PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Get milestone
            const milestone = process.env.MILESTONE_NUMBER

            // Find a milestone
            const response = await github.issues.listMilestones(context.repo)
            let githubMilestone = response.data.find(milestoneResponse => milestoneResponse.title === milestone)

            // Create new milestone if it doesn't exist
            if (!githubMilestone) {
              const createMilestoneResponse = await github.issues.createMilestone({ owner: context.repo.owner, repo:context.repo.repo, title: milestone })
              githubMilestone = createMilestoneResponse.data
            }

            // Sets the milestone to PR
            await github.issues.update({ owner: context.repo.owner, repo: context.repo.repo, milestone: githubMilestone.number, issue_number: context.issue.number })
